const data = [
  {
    cn: "USA",
    un: [
      "University of Connecticut, Storrs, Connecticut (Public Ivy)",
      "Johns Hopkins University, Baltimore, Maryland (School of Engineering – Only PG)",
      "Arizona State University, Phoenix, Arizona",
      "University of Massachusetts Amherst, Amherst, Massachusetts (Masters Programs)",
      "University of California, Riverside, California (Graduate Business Programs & College of",
      "Engineering and UCR Extension)",
      "Virginia Tech Language and Culture Institute, Blacksburg, Virginia (UG and PG Pathways)",
      "University of South Florida, Tampa, Florida (Only UG)",
      "University of Arizona, Tucson, Arizona",
      "Drexel University, Philadelphia, Pennsylvania (College of Engineering, UG Gateways and IEP)",
      "University of Delaware, Newark, Delaware (Only UG)",
      "Miami University, Oxford, Ohio (Public Ivy)",
      "University of Vermont, Burlington, Vermont (Only UG)",
      "Lehigh University, Bethlehem, Pennsylvania (Only PG)",
      "University of Oregon, Eugene, Oregon",
      "George Mason University, Fairfax County, Virginia",
      "The University of Oklahoma, Norman, Oklahoma",
      "Colorado State University, Fort Collins, Colorado",
      "Oregon State University, Corvallis, Oregon",
      "University of Illinois at Chicago, Chicago, Illinois (Only UG)",
      "The University of Alabama, Tuscaloosa, Alabama",
      "Claremont Graduate University, Claremont, California",
      "Auburn University, Auburn, Alabama",
      "University of Utah, Salt Lake City, Utah (Only UG)",
      "University of Cincinnati, Cincinnati, Ohio",
      "Ohio University, Athens, Ohio (Only UG)",
      "University of South Carolina, Columbia, South Carolina",
      "University of the Pacific, Stockton, California",
      "University of the Pacific",
      "University of Kansas, Lawrence, Kansas (Only UG)",
      "University of Tulsa, Tulsa, Oklahoma",
      "Montclair State University, Montclair, New Jersey",
      "University of Maryland, Baltimore County, Maryland",
      "University of Tennessee at Chattanooga, Chattanooga, Tennessee",
      "University at Albany, The State University of New York at Albany (SUNY Albany)",
      "University of Dayton, Dayton, Ohio",
      "University of Colorado Denver, Denver, Colorado",
      "Southern Illinois University, Carbondale, Illinois",
      "University of Colorado, Colorado Springs, Colorado",
      "State University of New York at Geneseo (SUNY Geneseo), Geneseo, New York",
      "SUNY Polytechnic Institute (SUNY Poly), Utica, New York",
      "The State University of New York at New Paltz (SUNY New Paltz)",
      "State University of New York at Fredonia (SUNY Fredonia), Fredonia, New York",
      "State University of New York College at Old Westbury (SUNY Old Westbury), Old Westbury, New York",
      "State University of New York at Oswego (SUNY Oswego), Oswego, New York",
      "Queens College, City University of New York",
      "Louisiana State University, Baton Rouge, Louisiana (Only UG)",
      "Worcester Polytechnic Institute, Worcester, Massachusetts",
      "Washington State University – Pullman, Tri Cities, Everett, Vancouver, and Spokane Campus",
      "University of Nebraska-Lincoln, Lincoln, Nebraska (Only UG)",
      "University of Alabama at Birmingham, Birmingham, Alabama",
      "Virginia Commonwealth University, Richmond, Virginia",
      "Saint Louis University, St. Louis, Missouri",
      "Missouri University of Science and Technology, Rolla, Missouri",
      "University of Massachusetts Lowell, Lowell, Massachusetts",
      "Clark University, Worcester, Massachusetts",
      "Massachusetts College of Pharmacy and Health Sciences, Boston, Massachusetts (MCPHS University)",
      "University of Massachusetts, Boston, Massachusetts (UG, PG Pathway and Direct Entry)",
      "University of Massachusetts, Dartmouth, Massachusetts",
      "Suffolk University, Boston, Massachusetts",
      "University of New Hampshire, Durham, New Hampshire",
      "Adelphi University, New York- Garden City and Manhattan Campus",
      "University of Idaho, Moscow, Idaho",
      "San Jose State University, San Jose, California",
      "San Francisco State University, San Francisco, California",
      "California State University, Los Angeles, California",
      "California State University, Chico, California",
      "California State University, Northridge, California",
      "California State University, Fresno, California",
      "California State University, East Bay, California",
      "California State University, Channel Islands, California",
      "California State University, Sacramento, California",
      "California State University, Bakersfield, California",
      "California State University, Dominguez Hills, California",
      "California State University, Stanislaus, California",
      "California State University, San Bernardino, California",
      "Sonoma State University, Rohnert Park, California",
      "California State Polytechnic University, Pomona (College of the Extended University)",
      "University of California, Irvine, California (Division of Continuing Education)",
      "University of California, Berkeley Extension, California",
      "University of California, Santa Cruz, Silicon Valley Extension (Professional Education)",
      "University of California, Santa Cruz, Silicon Valley Extension (Professional Education)",
      "University of Central Florida, Orlando, Florida (Only PG)",
      "New Jersey Institute of Technology, Newark, New Jersey",
      "Rochester Institute of Technology, Rochester, New York",
      "Fairleigh Dickinson University, Teaneck, New Jersey",
      "Portland State University, Portland, Oregon (Only UG)",
      "Florida Institute of Technology, Melbourne, Florida",
      "Pace University, Westchester & New York City Campus",
      "Drew University, Madison, New Jersey",
      "Whittier College, Whittier, California (Only UG)",
      "Savannah College of Art and Design, Savannah and Atlanta Campus, Georgia",
      "DePaul University, Chicago, Illinois",
      "University of South Dakota, Vermillion, South Dakota",
      "University of Hartford, West Hartford, Connecticut (Direct Entry and UG/PG Pathway)",
      "Sacred Heart University, Fairfield, Connecticut",
      "Florida International University,",
      "Kent State University, Kent, Ohio",
      "The University of Toledo, Toledo, Ohio (Only UG)",
      "University of Denver, Colorado (Daniel’s College of Business only)",
    ],
    cr: [
      "Mechanical Engineering",
      "Electrical Engineering",
      "Civil Engineering",
      "Computer Engineering",
      "Aerospace Engineering",
      "Finance",
      "Marketing",
      "Operations Management",
      "Entrepreneurship",
      "Human Resource Management",
      "Artificial Intelligence",
      "Data Science",
      "Cyber Security",
      "Software Development",
      "Cloud Computing",
      "Biotechnology",
      "Physics",
      "STEM MBA",
      "Chemistry",
      "Mathematics",
      "Pharmacy",
      "Public Health",
      "Nursing",
      "Biomedical Sciences",
    ],
  },
  {
    cn: "Canada",
    un: [
      "University of Alberta, Edmonton, Alberta(Only UG)",
      "University of Waterloo, Waterloo, Ontario",
      "University of Ottawa, Ottawa, Ontario",
      "Queen's University, Kingston, Ontario (Only UG)",
      "University of Calgary Continuing Education, Calgary, Alberta",
      "Dalhousie University, Halifax, Nova Scotia",
      "University of Victoria in Partnership with Kaplan, Victoria, British Columbia",
      "York University, School of Continuing Education, Toronto, Ontario",
      "University of Guelph, Guelph and Ridgetown Campus, Ontario",
      "University of Windsor, Windsor, Ontario",
      "University of Manitoba, Winnipeg, Manitoba",
      "Memorial University of Newfoundland, St. John's, Newfoundland and Labrador (Only PG)",
      "Memorial University of Newfoundland, Grenfell Campus, Newfoundland and Labrador (Only UG)",
      "University of New Brunswick, Fredericton and Saint John Campus, New Brunswick",
      "Carleton University, Ottawa, Ontario",
      "Toronto Metropolitan University, Toronto, Ontario",
      "University of Regina, Regina, Saskatchewan",
      "Brock University, St. Catharines, Ontario",
      "Wilfrid Laurier University, Waterloo, Ontario",
      "University of Lethbridge, Lethbridge, Alberta (Only UG)",
      "Lakehead University, Thunder Bay, Ontario",
      "University of Winnipeg, Winnipeg, Manitoba",
      "University of Prince Edward Island, Charlottetown, Prince Edward Island",
      "Acadia University, Wolfville, Nova Scotia (Only UG)",
      "St. Francis Xavier University, Antigonish, Nova Scotia",
      "University of Northern British Columbia, Prince George, British Columbia",
      "Laurentian University, Sudbury, Ontario (Except students from South Asia)",
      "Thompson Rivers University, Kamloops, British Columbia",
      "Ontario Tech University, Oshawa, Ontario",
      "Mount Saint Vincent University, Halifax, Nova Scotia",
      "Trent University, Peterborough, Ontario",
      "Trinity Western University, Langley, British Columbia",
      "Royal Roads University, Victoria, British Columbia",
      "Fairleigh Dickinson University, Vancouver, British Columbia",
      "Simon Fraser University through Fraser International College, Burnaby, British Columbia (Only UG)",
      "University of Alberta in Partnership with Kaplan, Edmonton, Alberta (Foundation programs)",
      "Wilfrid Laurier University through Wilfrid Laurier International College, Brantford, Ontario (Only UG)",
      "University of Manitoba through International College of Manitoba, Winnipeg, Manitoba (Only UG)",
      "University of Lethbridge through ULethbridge International College Calgary (UICC), Calgary, Alberta (Only UG)",
      "Toronto Metropolitan University through Toronto Metropolitan International College, Toronto, Ontario (Only UG)",
      "Vancouver Island University, Nanaimo, British Columbia",
      "St. Thomas University, Fredericton, New Brunswick (Only UG)",
      "University Canada West, Vancouver, British Columbia",
      "New York Institute of Technology, Vancouver, British Columbia",
      "Nipissing University, North Bay, Ontario",
      "Adler University, Vancouver, British Columbia",
      "King’s University College (University of Western Ontario), London, Ontario",
      "Cape Breton University, Sydney, Nova Scotia",
      "Capilano University, North Vancouver, British Columbia",
      "Kwantlen Polytechnic University, Surrey, British Columbia",
      "University of the Fraser Valley, Abbotsford, British Columbia",
      "University of the Fraser Valley",
      "Mount Allison University, Sackville, New Brunswick",
      "MacEwan University, Edmonton, Alberta (Only UG)",
      "University of Niagara Falls, Niagara, Ontario",
      "University of Niagara Falls, Niagara, Ontario",
      "Crandall University, Moncton and Sussex, New Brunswick",
      "City University in Canada, Calgary and Edmonton, Alberta (Master of Education in Leadership program only)",
      "City University in Canada, Vancouver, British Columbia (Master of Education in Leadership program only)",
      "Providence University College, Winnipeg, Manitoba (Master of Management program only)",
      "Niagara University, Vaughan, Ontario (Only PG)",
      "International Business University, Toronto, Ontario (Except students from South Asia and Africa)",
      "Seneca Polytechnic, Toronto, Ontario",
      "Humber Polytechnic, Toronto, Ontario",
      "George Brown College, Toronto, Ontario",
      "Sheridan College, Oakville, Ontario",
      "Bow Valley College, Calgary, Alberta",
      "St. Clair College of Applied Arts & Technology, Windsor, Ontario",
      "Douglas College, New Westminster, British Columbia (Except students from Punjab, Haryana and Chandigarh)",
      "Southern Alberta Institute of Technology, Calgary, Alberta",
      "Northern Alberta Institute of Technology (NAIT), Edmonton, Alberta",
      "Niagara College, Welland, Ontario",
      "Fanshawe College, London, Ontario",
      "Durham College, Oshawa, Ontario",
      "Fleming College, Peterborough, Ontario",
      "North Island College, Vancouver Island, British Columbia",
      "Georgian College, Barrie, Ontario",
      "Langara College, Vancouver, British Columbia (Except students from Punjab and Haryana)",
      "Lakeland College, Lloydminster and Vermilion, Alberta",
      "Cambrian College, Sudbury, Ontario",
      "Manitoba Institute of Trades and Technology, Winnipeg, Manitoba",
      "Conestoga College, Kitchener, Ontario",
      "College of New Caledonia, Prince George, British Columbia",
      "Saskatchewan Polytechnic, Saskatoon, Saskatchewan",
      "LaSalle College, Montreal and Vancouver",
      "College of the Rockies, Cranbrook, British Columbia",
      "Northern Lights College, Dawson Creek, British Columbia",
      "Northern College, Timmins, Ontario",
      "Booth University College, Winnipeg, Manitoba",
      "St. Lawrence College, Kingston, Ontario",
      "Lambton College, Sarnia and Ottawa, Ontario",
      "Selkirk College, Castlegar, British Columbia",
      "Assiniboine College, Brandon, Winnipeg and Dauphin Campus, Manitoba",
      "Keyano College, Fort McMurray, Alberta",
      "Canadore College, North Bay, Ontario (Except students from Punjab and Haryana)",
      "Acsenda School of Management, Vancouver, British Columbia",
      "Vancouver Film School, Vancouver, British Columbia",
      "Vancouver Community College, Vancouver, British Columbia",
      "British Columbia Institute of Technology, Burnaby, British Columbia",
      "Medicine Hat College, Medicine Hat, Alberta",
    ],
    cr: [
      "Engineering",
      "Management",
      "Information technology",
      "Health Sciences",
      "Financial accounting",
      "Human Resources",
      "Journalism",
      "Architecture",
      "Business",
      "Agricultural and forestry",
      "Project management",
      "Psychology",
      "Applied Health",
      "Computer Engineering",
      "Computer programming",
      "Cyber security",
      "Data science",
      "Diploma in Accounting",
      "Hospitality management studies",
      "Master of Business Administration",
      "Animation and Multimedia courses",
    ],
  },
  {
    cn: "Uk",
    un: [
      "University of Bristol, Bristol, England",
      "University of Glasgow, Glasgow, Scotland",
      "University of Glasgow",
      "University of Southampton, Southampton, England",
      "University of Birmingham, Birmingham, England",
      "University of Leeds, Leeds, England",
      "Durham University, Durham, England",
      "The University of Sheffield, Sheffield, England",
      "University of Nottingham, Nottingham, England",
      "Queen Mary University of London, London, England",
      "Newcastle University, Newcastle upon Tyne, England",
      "Lancaster University, Lancaster, England",
      "University of Bath, Bath, England",
      "University of Liverpool, Liverpool, England",
      "The University of Exeter, Exeter, England",
      "University of Reading, Reading, England",
      "Cranfield University, Cranfield, England",
      "University of York, York, England",
      "Cardiff University, Cardiff, Wales",
      "Queen`s University Belfast, Belfast, Northern Ireland",
      "Loughborough University, Loughborough & London, England",
      "University of Aberdeen, Aberdeen, Scotland",
      "University of Sussex, Brighton, England",
      "Heriot Watt University, Edinburgh, Scotland",
      "University of Strathclyde, Glasgow, Scotland",
      "University of Surrey , Guildford, England",
      "University of Leicester, Leicester, England",
      "Swansea University, Swansea, Wales",
      "University of East Anglia, Norwich, England",
      "Brunel University of London, London, England",
      "City St George's, University of London, London, England",
      "University of Kent, Canterbury, England",
      "Oxford Brookes University, Oxford, England",
      "University of Dundee, Dundee, Scotland",
      "Aston University, Birmingham, England",
      "University of Stirling, Stirling, Scotland",
      "University of Essex, Colchester, England",
      "Bangor University, Bangor, Wales",
      "Royal Holloway, University of London, Egham, England",
      "The University of Huddersfield, Huddersfield, England",
      "SOAS University of London, London, England",
      "The University of Huddersfield, London, England",
      "University of Hull, Hull, England",
      "University of Hull, London Campus, England",
      "Coventry University, Coventry & London, England",
      "University of Bradford, Bradford, England",
      "Northumbria University, Newcastle upon Tyne & London, England",
      "Nottingham Trent University, Nottingham, England",
      "Manchester Metropolitan University, Manchester, England",
      "Kingston University, Kingston, England",
      "University of Portsmouth, Portsmouth & London, England",
      "University of Plymouth, Plymouth, England",
      "Aberystwyth University, Aberystwyth, Wales",
      "Goldsmiths, University of London, London, England",
      "University of Greenwich, London, England",
      "De MontFort University, Leicester, England",
      "Middlesex University, London, England",
      "University of the West of England, Bristol, England",
      "Keele University, Keele, England",
      "University of Brighton, Brighton, England",
      "Edinburgh Napier University, Edinburgh, Scotland",
      "London South Bank University, London, England",
      "University of Hertfordshire, Hatfield, England",
      "University of Lincoln, Lincoln, England",
      "University of East London, London, England",
      "University of Salford, Manchester, England",
      "Robert Gordon University, Aberdeen, Scotland",
      "Robert Gordon University, Aberdeen, Scotland",
      "University of Lancashire, Preston, England",
      "London Metropolitan University, London, England",
      "Birmingham City University, Birmingham, England",
      "Sheffield Hallam University, Sheffield, England",
      "The University of Northampton, Northampton, England",
      "Leeds Beckett University, Leeds, England",
      "University of Derby, Derby, England",
      "Canterbury Christ Church University, Canterbury, England",
      "University of Wolverhampton, Wolverhampton, England",
      "Anglia Ruskin University, Cambridge & Chelmsford, England (Except Punjab and Haryana)",
      "Teesside University (Except Namakkal & Punjab), Middlesbrough and London Campus",
      "University of Suffolk, London, England",
      "University of Suffolk, London, England",
      "University of the West of Scotland, Paisley, Scotland",
      "University of the West of Scotland, London Campus, England",
      "University of South Wales (Except Punjab & Haryana), Cardiff, Wales",
      "University of South Wales",
      "University of Roehampton, London, England",
      "University of Staffordshire, Stoke-on-Trent, England",
      "University of Sunderland, Sunderland & London, England",
      "University of Bedfordshire, Luton, England",
      "Cardiff Metropolitan University, Cardiff , Wales",
      "University of Chester, Chester, England",
      "University of Gloucestershire, Gloucester, England",
      "University of West London, London, England",
      "York St John University, York, England",
      "University of Greater Manchester, Bolton, England",
      "Abertay University, Dundee, Scotland",
      "Liverpool Hope University, Liverpool, England",
      "University of Wales Trinity Saint David, London, Birmingham and Swansea Campus, England & Wales",
      "St. Mary’s University, Twickenham, England",
      "Southampton Solent University, Southampton, England",
    ],
    cr: [
      "Architecture",
      "Engineering",
      "Law",
      "Computer Science",
      "Business analytics",
      "MBA",
      "Medicine",
      "Data science",
      "Financial accounting",
      "Psychology",
      "Economics",
      "Education",
      "Nursing",
      "Fashion and interior designing",
      "Bachelor of medicine, bachelor of Surgery",
    ],
  },
  {
    cn: "Australia",
    un: [
      "The University of New South Wales, Sydney",
      "Monash University, Melbourne",
      "The University of Queensland, Brisbane)",
      "University of Western Australia, Perth",
      "The University of Adelaide,",
      "University of Technology Sydney, Sydney",
      "Adelaide University, Adelaide",
      "Adelaide University, Adelaide",
      "RMIT University, Melbourne",
      "Macquarie University, Sydney",
      "Macquarie University",
      "University of Wollongong, Wollongong",
      "Deakin University, Melbourne, Geelong & Warrnambool Campus",
      "Queensland University of Technology, Brisbane",
      "La Trobe University, Melbourne & Sydney",
      "Griffith University, Gold Coast & Brisbane (CRICOS Code 00233E)",
      "Swinburne University of Technology, Melbourne",
      "University of Tasmania, Hobart, Launceston, Sydney",
      "University of Tasmania, Melbourne",
      "Flinders University, Adelaide",
      "University of South Australia, Adelaide",
      "Western Sydney University, Sydney City Campus",
      "Murdoch University, Perth Campus",
      "University of Canberra, Sydney Hills",
      "James Cook University, Townsville, Cairns & Brisbane",
      "CQUniversity Australia, Sydney, Melbourne, Brisbane & Perth",
      "Charles Darwin University, Darwin",
      "Victoria University, Sydney & Brisbane",
      "Victoria University, Sydney",
      "Charles Sturt University, Sydney & Melbourne",
      "University of the Sunshine Coast, Adelaide",
      "The University of Notre Dame Australia, Fremantle",
      "S P Jain School of Global Management, Sydney Campus",
      "UNSW College, Sydney",
      "The University of Adelaide College",
      "UTS College, Sydney",
      "Charles Darwin University International",
      "Engineering Institute of Technology,",
      "ECA College of Health Sciences, Brisbane & Sydney",
      "Asia Pacific International College, Sydney & Melbourne",
      "Higher Education Leadership Institute, Melbourne",
      "Le Cordon Bleu, Adelaide, Sydney, Melbourne & Perth",
      "Kaplan Business School, Sydney (Only PG)",
      "International College of Management Sydney",
      "Academy of Interactive Technology, Sydney",
      "Academy of Information Technology, Sydney",
      "Excelsia University College, Sydney",
      "Ironwood Institute Adelaide, Adelaide",
      "Australian College of Applied Professions, Sydney",
      "The University of Newcastle College of International Education, Newcastle",
      "Curtin College, Perth",
      "Deakin College, Melbourne",
      "South Australia Institute of Business & Technology, Adelaide",
      "Griffith College, Gold Coast & Brisbane",
      "La Trobe College, Melbourne",
      "Sydney Institute of Business & Technology, Sydney",
      "Edith Cowan College",
      "Eynesbury College, Adelaide",
      "University of Canberra College, Canberra",
      "Russo Business School, Brisbane",
      "LaSalle College, Melbourne",
      "Sarina Russo Institute, Brisbane",
      "Analytics Institute of Australia, Melbourne",
    ],
    cr: [
      "Engineering",
      "Accountancy",
      "Hospitality",
      "Business analytics",
      "Nursing",
      "Computer Science",
      "Medicine",
      "Psychology",
      "Actuarial science",
      "Architecture",
      "Earth sciences",
      "Agricultural science",
      "Construction managers",
      "Education",
      "Civil Engineering",
      "Barnbougle Lost Farm Golf Resort",
      "BBA in Australia",
      "Management",
      "Core Engineering",
      "Information technology",
      "Kingston Heath Golf Club",
      "Medicine courses in Australia",
      "Chef",
      "Financial Analyst",
    ],
  },
  {
    cn: "New Zealand",
    un: [
      "University of Auckland, Auckland",
      "University of Otago, Dunedin",
      "Massey University, Palmerston North",
      "Victoria University of Wellington, Wellington",
      "University of Waikato, Hamilton",
      "University of Canterbury, Christchurch",
      "Lincoln University, Lincoln",
      "Auckland University of Technology, Auckland",
      "Unitec Institute of Technology, Auckland",
      "Otago Polytechnic, Dunedin & Auckland",
      "Manukau Institute of Technology - Te Pūkenga, Auckland",
      "Ara Institute of Canterbury, Christchurch",
      "Eastern Institute of Technology, Napier",
      "Waikato Institute of Technology (Wintec), Hamilton",
      "Waikato Institute of Technology (Wintec) - Te Pūkenga",
      "Nelson Marlborough Institute of Technology (NMIT), Nelson & Blenheim",
      "Whitireia New Zealand, Porirua",
      "Southern Institute of Technology, Invercargill",
      "Wellington Institute of Technology (WelTec), Wellington",
      "Western Institute of Technology at Taranaki (WITT), New Plymouth",
      "North Tec, Whangarei",
      "The Universal College of Learning (UCOL), Palmerston North",
      "Toi Ohomai Institute of Technology, Rotorua & Tauranga",
      "New Zealand Skills and Education Group, Auckland",
      "Pacific International Hotel Management School, New Plymouth",
      "New Zealand Tertiary College (NZTC), Auckland",
      "Future Skills Academy, Auckland",
      "UC International College, Christchurch",
      "The University of Auckland International College",
      "University of Waikato College, Hamilton",
      "Whitecliffe College of Arts and Design, Auckland & Christchurch",
      "Whitecliffe College of Fashion and Sustainability, Auckland & Wellington",
      "Whitecliffe College of Technology & Innovation, Auckland, Wellington & Christchurch",
      "Le Cordon Bleu, Wellington",
      "New Zealand Airline Academy, Oamaru",
      "AcademyEX Education, Auckland",
      "New Zealand Management Academies (NZMA), Auckland",
      "New Zealand Industry Training Enterprise (NZITE), Auckland",
    ],
    cr: [
      "IT & Computer Science",
      "MBA",
      "Healthcare",
      "Engineering",
      "Tourism/Hospitality Management",
      "Law",
      "Architecture",
      "Sports Management",
      "Agriculture",
      "Accounting",
      "Animation and Web Design",
    ],
  },
  {
    cn: "France",
    un: [
      "INSEEC Business School, Paris",
      "NEOMA Business School, Rouen",
      "ESCE International Business School, Paris",
      "ECE Engineering School, Paris",
      "(Navitas) ICN International College, Paris",
      "SupdePub School of Creation and Communication, Paris",
      "HEIP, School of International and Political Studies, Paris",
      "Excelia Group, La Rochelle",
      "ICN Business School, Nancy and Paris Campus",
      "Kedge Business School, Talence",
      "Montpellier Business School, Montpellier",
      "ESSCA School of Management, Angers",
      "EM Normandie Business School, Paris",
      "Clermont School of Business, Clermont-Ferrand",
      "ESC Clermont Business School, Clermont-Ferrand",
      "Skema Business School, Paris",
      "Burgundy School of Business, Dijon",
      "Institut supérieur d`électronique de Paris (ISEP), Paris",
      "EPITA - School of Engineering and Computer Science, Paris",
      "ESIGELEC, Rouen",
      "Institut supérieur du commerce de Paris - ISC, Paris",
      "Le Cordon Bleu, Paris",
      "De Vinci Higher Education, Paris",
      "College de Paris, Paris",
      "Queen Mary University of London, Paris",
      "Instituto Marangoni Fashion and Design School, Paris",
      "The American Business School of Paris, Paris",
      "Ecole Ducasse, Paris",
      "Berlin School of Business and Innovation, Paris",
      "ICD Business School, Paris",
      "Schiller International University, Paris Campus",
      "École de Management Appliqué, Paris",
      "Paris School of Business, Paris",
      "ESDES School of Business and Management, Lyon",
      "EPITECH, Paris",
      "HEAD School of Law, Paris",
    ],
    cr: [
      "Engineering",
      "Fashion design",
      "Computer Science",
      "Data science",
      "Film Studies",
      "Finance",
      "Hospitality management studies",
      "Luxury brand Management",
      "Medicine",
      "Engineering and technology",
    ],
  },
  {
    cn: "Germany",
    un: [
      "Constructor University",
      "Jacobs University",
      "Steinbeis University, Berlin (Only PG)",
      "SRH University, Berlin, Hamburg, Leipzig, Dresden, Munich and Heidelberg Campuses",
      "SRH Berlin University of Applied Sciences",
      "SRH Fernhochschule – The Distance Learning University, Riedlingen",
      "Northern Institute of Technology Management (NIT), Hamburg",
      "Hamburg University of Technology (TUHH), Hamburg",
      "FOM Hochschule - University of Applied Sciences for Economics and Management, Essen",
      "EBS University, Wiesbaden",
      "International School of Management, Dortmund",
      "International University of Applied Sciences, Berlin and Bad Honnef",
      "CBS International Business School, Cologne",
      "Arden University, Berlin",
      "GISMA University of Applied Sciences GmbH, Berlin",
      "New European College, Munich",
      "EU Business School, Munich",
      "Munich Business School, Munich",
      "Accadis Hochschule Bad Homburg - University of Applied Sciences, Bad Homburg",
      "Berlin School of Business and Innovation, Berlin",
      "Fresenius University of Applied Sciences, Idstein",
      "University of Europe for Applied Sciences, Hamburg",
      "Hochschule Macromedia University of Applied Sciences, Munich",
      "ICN Business School, Berlin Campus",
      "Navitas - Lancaster University, Leipzig",
      "EIIE Eurasia Institute for International Education GmbH, Berlin (Except students from Gujarat, Punjab and Haryana)",
      "University Targu Mures Medical Campus, Hamburg (UMCH)",
      "Media Design University of Applied Sciences, Berlin",
      "Schiller International University, Heidelberg Campus",
      "PFH – Private University of Applied Sciences, Göttingen",
    ],
    cr: [
      "Engineering",
      "Computer Science and IT",
      "Business Management",
      "Social Sciences",
      "Humanities and Creative Arts",
    ],
  },
  {
    cn: "Denmark",
    un: [
      "Aarhus University, Aarhus",
      "University of Southern Denmark, Odense and Sonderborg Campus",
      "International Business Academy, Kolding",
      "VIA University College, Horsens and Herning Campus",
    ],
    cr: [
      "Engineering and Technology",
      "Business and Management",
      "Life Sciences and Environmental Sciences",
      "Design and Creative Arts",
      "Social Sciences and Humanities",
    ],
  },
  {
    cn: "Finland",
    un: [
      "Aalto University, Espoo",
      "University of Turku, Turku",
      "LUT University, Lappeenranta",
      "Tampere University, Tampere",
      "University of Jyväskylä, Jyväskylä",
      "Tampere University of Applied Sciences (TAMK), Tampere",
      "Turku University of Applied Sciences, Turku",
      "University of Eastern Finland, Kuopio",
      "LAB University of Applied Sciences, Lahti",
      "University of Vaasa, Vaasa",
      "Vaasa University of Applied Sciences VAMK, Vaasa",
      "Karelia University of Applied Sciences, Joensuu",
      "Metropolia University of Applied Sciences, Helsinki",
      "Satakunta University of Applied Sciences (SAMK), Pori",
      "Arcada University of Applied Sciences, Helsinki",
      "Hanken School of Economics, Helsinki",
    ],
    cr: [
      "Information Technology (IT),",
      "Business Administration,",
      "Engineering,",
      "Sustainability studies and Environmental Sciences",
      "Health Sciences and Biotechnology",
      "Arts, Design, and Architecture",
      "Social Sciences",
    ],
  },
  {
    cn: "Italy",
    un: [
      "University of Padua, Padua",
      "Istituto Europeo di Design - IED, Milan",
      "Istituto Marangoni Fashion and Design School, (Milan and Florence Campus)",
      "Nuova Accademia di Belle Arti (NABA School), Milan",
      "Domus Academy, Milan",
      "Raffles Milano- Instituto Moda e Design, Milan",
      "LUISS Guido Carli, Rome",
      "Guglielmo Marconi University, Rome",
      "Polimi Graduate School of Management, Italy",
    ],
    cr: [
      "Hospitality Management",
      "Business Management",
      "Economics",
      "Humanities",
      "Masters in fashion design",
      "BA in Italy",
      "Engineering",
      "International Relations",
      "MBA",
      "Sciences",
      "Fashion and luxury goods management",
    ],
  },
  {
    cn: "Cyprus",
    un: [
      "University of Nicosia, Nicosia",
      "University of Central Lancashire (UCLAN), Pyla",
      "Neapolis University Pafos, Pafos",
    ],
    cr: [
      "Business & Management,",
      "Engineering & Technology,",
      "Hospitality & Tourism,",
      "Computer Science & IT",
      "Psychology",
      "Law",
      "Health Sciences",
      "Social Sciences",
      "Aviation",
      "Food & Beverage Studies",
      "Architecture Studies",
    ],
  },
  {
    cn: "Malta",
    un: [
      "Queen Mary University of London, Malta Campus",
      "Ascencia Business School Malta",
      "College De Paris, Malta Campus (Ascencia Malta)",
      "Idea Academy, Malta",
      "London School of Commerce, Malta Campus",
      "Global Malta College (Except students from Punjab)",
      "Saint Martin’s Institute of Higher Education",
      "Global Business School – GBS Malta Campus",
      "Learnkey Training Institute",
      "Yhank Institute, Malta",
    ],
    cr: [
      "Engineering",
      "Information technology",
      "Economics",
      "Medicine",
      "Hospitality management studies",
      "Arts and design",
      "Business Administration",
      "Management",
      "Environmental science, ecology",
      "Law",
      "Natural Sciences",
      "Social Sciences",
      "Humanities",
      "Media and communication",
    ],
  },
  {
    cn: "Switzerland",
    un: [
      "University of Zurich, Zürich (Only PG)",
      "GLION Institute of Higher Education, Montreux",
      "EU Business School, Montreux and Geneva",
      "Business & Hotel Management School (BHMS), Lucerne",
      "Swiss Hotel Management School (SHMS), Montreux and Leysin",
      "Geneva Business School, Geneva",
      "Webster University Geneva, Geneva",
      "Swiss School of Business and Management (SSBM), Geneva",
      "International Management Institute (IMI), Kastanienbaum, Luzern",
      "Cesar Ritz, Montreux",
      "International University in Geneva, Geneva",
      "Hotel & Tourism Management Institute Switzerland (HTMi), Lucerne",
      "Les Roches, Montana",
      "lesroches.edu/campuses/crans-montana/",
      "Culinary Arts Academy (CAA), Le Bouveret and Lucerne",
      "Hotel Institute Montreux (HIM), Montreux",
      "American Institute of Applied Sciences in Switzerland, La Tour-de-Peilz",
      "EHL Swiss School of Tourism and Hospitality, Passugg Campus",
      "EHL Hospitality Business School, Lausanne Campus",
      "Swiss Education Academy, Montreux",
      "Swiss Educational College, Weggis",
      "Bella Vista Institute of Higher Education Switzerland (BVIS), Altdorf and Montreux",
      "S P Jain School of Global Management, India Campus",
    ],
    cr: [
      "Business management,",
      "Finance,",
      "Engineering, law,",
      "Computer science (IT)",
      "Hospitality & Tourism Management",
      "Applied Mathematics",
      "Artificial Intelligence",
      "Interdisciplinary Sciences",
      "Quantitative & Systems Biology",
      "Hotel & Hospitality Management",
      "International Business",
      "Mathematics",
      "Media & Films",
      "Psychology",
      "Arts",
      "Science",
      "Education & Training",
      "Medicine and Healthcare",
    ],
  },
  {
    cn: "Sweden",
    un: [
      "Uppsala University, Uppsala",
      "Linnaeus University, Kalmar and Växjö",
      "University of Skövde, Skovde",
      "Halmstad University, Halmstad",
      "University West, Trollhättan",
      "Jönköping University, Jönköping",
      "Dalarna University, Falun",
      "Kristianstad University, Kristianstad",
      "Karlstad University, Karlstad",
      "Hyper Island University, Stockholm",
    ],
    cr: [
      "Engineering",
      "Computer Science",
      "Environmental studies",
      "Law",
      "Mathematics",
      "Public Health",
      "Management",
      "Humanities",
      "Social Sciences",
      "Design and Creative Arts",
      "Plant and Forest biotechnology",
    ],
  },
  {
    cn: "Hungary",
    un: [
      "University of Debrecen, Debrecen",
      "Budapest University of Economics and Business, Budapest",
      "University of Pécs, Pécs",
      "Szechenyi Istvan University (University of Gyor), Gyor",
      "International Business School (IBS), Budapest (Except students from Punjab & South India)",
      "Budapest Metropolitan University of Applied Science, Budapest",
      "Wekerle Business School, Budapest",
    ],
    cr: [
      "Engineering",
      "Business & Finance",
      "Medicine & Healthcare",
      "Computer & IT Humanities",
      "Music",
    ],
  },
  {
    cn: "Netherlands",
    un: [
      "University of Twente, Enschede",
      "Radboud University, Nijmegen",
      "Maastricht School of Management, Maastricht",
      "Wittenborg University of Applied Sciences, Amsterdam and Apeldoorn Campus",
      "Tio Business School, Utrecht",
      "Tio University of Applied Sciences",
      "Unknown University of Applied Sciences, Amsterdam, The Hague",
      "Global School of Entrepreneurship",
      "The Hague University of Applied Sciences (UG Pathway), Hague",
      "University of Applied Sciences Europe, Amsterdam",
    ],
    cr: [
      "Engineering",
      "Business",
      "Management",
      "Computer Science",
      "Finance",
      "Sciences",
      "Economics",
      "Information technology",
      "International Relations",
      "MBA",
      "Natural Sciences",
      "Social Sciences",
    ],
  },
  {
    cn: "Ireland",
    un: [
      "Trinity College Dublin, Dublin",
      "University College Dublin, Dublin",
      "University of Galway, Galway",
      "University College Cork, Cork",
      "Dublin City University, Dublin",
      "University of Limerick, Limerick",
      "Maynooth University, Maynooth",
      "Technological University Dublin, Dublin",
      "South East Technological University (Waterford and Carlow Campus)",
      "Munster Technological University, Cork and Kerry Campus",
      "RCSI University of Medicine and Health Sciences",
      "Royal College of Surgeons in Ireland, Dublin",
      "Atlantic Technological University (Galway and Letterkenny Campus)",
      "Dundalk Institute of Technology, Dundalk",
      "Technological University of the Shannon: Midlands Midwest, Shannon (Limerick and Athlone Campus)",
      "National College of Ireland, Dublin",
      "Dublin Business School, Dublin",
      "Griffith College, Dublin, Cork and Limerick (Campus in 3 cities)",
      "Galway Business School, Galway",
      "Shannon College of Hotel Management, A college of NUI Galway, Galway",
      "Dublin International Foundation College, Dublin",
      "American College Dublin, Dublin",
      "UniHaven College, Maynooth",
      "IBAT College Dublin, Dublin",
      "Independent College, Dublin",
      "CCT College Dublin, Dublin",
    ],
    cr: [
      "Engineering",
      "Management",
      "Medicine",
      "Computer Science",
      "Computer Science in Ireland",
      "Data science",
      "Digital marketing",
      "Finance",
      "Science",
      "Business analytics",
      "Data analysis",
      "Engineering in Ireland",
      "Healthcare",
      "Pharmaceutical Sciences",
      "Social Sciences",
      "Artificial intelligence",
      "Cloud computing",
      "Computer security",
      "Hospitality and Tourism",
      "Software engineering",
      "Business Analytics in Ireland",
      "Medicine in Ireland",
    ],
  },
  {
    cn: "Singapore",
    un: [
      "National University of Singapore (SCALE and ISS courses)",
      "Technical University of Munich Asia (Only PG)",
      "Singapore University of Technology and Design (SUTD)",
      "Curtin Singapore",
      "James Cook University (JCU)",
      "Embry Riddle Aeronautical University Asia",
      "SIM Global Education",
      "S P Jain School of Global Management",
      "Management Development Institute of Singapore (MDIS)",
      "PSB Academy",
      "Raffles College of Higher Education",
      "Kaplan Higher Education Academy (KHEA)",
      "Kaplan Financial Education",
      "William Angliss Institute",
      "Nanyang Institute of Management",
      "East Asia Institute of Management",
      "XCL World Academy (Boarding School)",
    ],
    cr: [
      "MBA",
      "Hospitality and Tourism",
      "Computer Science",
      "Law",
      "Banking",
      "Management",
      "Engineering",
      "Information technology",
      "Architecture",
      "Healthcare",
      "Art",
      "Bachelor of Medicine and Bachelor of Surgery",
      "Bachelor of Engineering",
      "Finance",
      "Management and engineering",
      "Mass communication",
      "Environmental resource management",
      "Social science",
      "Urban planning",
      "BBA in Singapore",
      "Logistics and supply chain Management",
      "Postgraduate Diploma in Business Administration",
    ],
  },
  {
    cn: "Dubai",
    un: [
      "University of Birmingham, Dubai Campus",
      "University of Wollongong, Dubai Campus",
      "Curtin University, Dubai Campus",
      "Heriot Watt University, Dubai Campus",
      "Murdoch University, Dubai Campus",
      "Canadian University, Dubai",
      "Abu Dhabi University, Abu Dhabi & Dubai",
      "Symbiosis International University, Dubai Campus",
      "Middlesex University, Dubai Campus",
      "Bath Spa University, Ras Al-Khaimah",
      "American University in Dubai, Dubai",
      "De MontFort University, Dubai Campus",
      "University of Hertfordshire, Sharjah Campus",
      "Manipal Academy of Higher Education (MAHE), Dubai Campus",
      "Abu Dhabi University",
      "Birla Institute of Technology and Science (BITS Pilani), Dubai Campus",
      "Rochester Institute of Technology Dubai (RIT Dubai)",
      "Hult International Business School, Dubai Campus",
      "S P Jain School of Global Management, Dubai Campus",
      "University of Bolton Academic Centre, Ras Al Khaimah",
      "EM Normandie, Dubai Campus",
      "HTMI Switzerland, Dubai Campus",
      "American University of Ras Al Khaimah",
      "Synergy University, Dubai Campus",
      "Emirates Aviation University, Dubai",
      "University of Europe for Applied Sciences, Dubai",
      "Istituto Marangoni Fashion and Design School, Dubai",
      "Abu Dhabi Hospitality Academy - Les Roches, Abu Dhabi Campus",
      "Institute of Management Technology (IMT), Dubai",
      "Global Business Studies - GBS Dubai",
      "Idea Academy, Dubai (Except Students from Punjab and Haryana)",
      "UK College of Business and Computing, Dubai Campus",
      "Regent College, Dubai Campus",
      "Institute of Business, Technology and Engineering (IBTE), Dubai",
    ],
    cr: [
      "Management",
      "Engineering",
      "Hospitality and Tourism Management",
      "Medicine and healthcare",
      "Computer science and IT",
      "Media and communication",
      "Architecture",
      "Financial accounting",
      "Education",
      "Art and Design",
      "Healthcare",
    ],
  },
  {
    cn: "Malaysia",
    un: [
      "Monash University, Malaysia Campus",
      "University of Southampton, Malaysia Campus",
      "University of Nottingham, Malaysia Campus",
      "University of Wollongong, Malaysia Campus",
      "Heriot-Watt University, Malaysia Campus",
      "Taylor`s University, Malaysia",
      "Swinburne University, Malaysia Campus",
      "UCSI University, Kuala Lumpur",
      "Asia Pacific University of Technology And Innovation, Kuala Lumpur",
      "Sunway Le Cordon Bleu",
      "Raffles University, Malaysia Campus",
      "Raffles College of Higher Education, Kuala Lumpur",
      "MDIS Malaysia, Gelang Patah",
    ],
    cr: [
      "Engineering",
      "Accounting",
      "IT",
      "Mass communication",
      "Aerospace engineering",
      "Architecture",
      "Biomedical engineering",
      "Civil Engineering",
      "Medicine",
      "Social Sciences",
      "Computer Science",
      "Economics",
      "Electrical engineering",
      "Environmental studies",
      "Healthcare courses",
      "Humanities",
      "Marketing",
      "Software engineering",
      "Management",
      "Business Administration",
      "Creative Arts and Media",
    ],
  },
  {
    cn: "Japan",
    un: [
      "International College of Liberal Arts, Kofu",
      "Tokyo International University, Kawagoe",
      "Kudan Institute of Japanese language & Culture, Tokyo",
    ],
    cr: [
      "Engineering",
      "Medicine",
      "Business",
      "Agriculture",
      "Commerce",
      "Economics",
      "Education",
      "Environmental Science",
      "Language and cultural Studies",
      "Law",
      "Sports science",
    ],
  },
];

export default data;

// const data = [
//   {
//     cn: "USA",
//     un: [
//       "1. University of Connecticut, Storrs, Connecticut (Public Ivy)",
//       "2. Johns Hopkins University, Baltimore, Maryland (School of Engineering – Only PG)",
//       "3. Arizona State University, Phoenix, Arizona",
//       "4. University of Massachusetts Amherst, Amherst, Massachusetts (Masters Programs)",
//       "5. University of California, Riverside, California (Graduate Business Programs & College of",
//       "6. Engineering and UCR Extension)",
//       "7. Virginia Tech Language and Culture Institute, Blacksburg, Virginia (UG and PG Pathways)",
//       "8. University of South Florida, Tampa, Florida (Only UG)",
//       "9. University of Arizona, Tucson, Arizona",
//       "10. Drexel University, Philadelphia, Pennsylvania (College of Engineering, UG Gateways and IEP)",
//       "11. University of Delaware, Newark, Delaware (Only UG)",
//       "12. Miami University, Oxford, Ohio (Public Ivy)",
//       "13. University of Vermont, Burlington, Vermont (Only UG)",
//       "14. Lehigh University, Bethlehem, Pennsylvania (Only PG)",
//       "15. University of Oregon, Eugene, Oregon",
//       "16. George Mason University, Fairfax County, Virginia",
//       "17. The University of Oklahoma, Norman, Oklahoma",
//       "18. Colorado State University, Fort Collins, Colorado",
//       "19. Oregon State University, Corvallis, Oregon",
//       "20. University of Illinois at Chicago, Chicago, Illinois (Only UG)",
//       "21. The University of Alabama, Tuscaloosa, Alabama",
//       "22. Claremont Graduate University, Claremont, California",
//       "23. Auburn University, Auburn, Alabama",
//       "24. University of Utah, Salt Lake City, Utah (Only UG)",
//       "25. University of Cincinnati, Cincinnati, Ohio",
//       "26. Ohio University, Athens, Ohio (Only UG)",
//       "27. University of South Carolina, Columbia, South Carolina",
//       "28. University of the Pacific, Stockton, California",
//       "29. University of the Pacific",
//       "30. University of Kansas, Lawrence, Kansas (Only UG)",
//       "31. University of Tulsa, Tulsa, Oklahoma",
//       "32. Montclair State University, Montclair, New Jersey",
//       "33. University of Maryland, Baltimore County, Maryland",
//       "34. University of Tennessee at Chattanooga, Chattanooga, Tennessee",
//       "35. University at Albany, The State University of New York at Albany (SUNY Albany)",
//       "36. University of Dayton, Dayton, Ohio",
//       "37. University of Colorado Denver, Denver, Colorado",
//       "38. Southern Illinois University, Carbondale, Illinois",
//       "39. University of Colorado, Colorado Springs, Colorado",
//       "40. State University of New York at Geneseo (SUNY Geneseo), Geneseo, New York",
//       "41. SUNY Polytechnic Institute (SUNY Poly), Utica, New York",
//       "42. The State University of New York at New Paltz (SUNY New Paltz)",
//       "43. State University of New York at Fredonia (SUNY Fredonia), Fredonia, New York",
//       "44. State University of New York College at Old Westbury (SUNY Old Westbury), Old Westbury, New York",
//       "45. State University of New York at Oswego (SUNY Oswego), Oswego, New York",
//       "46. Queens College, City University of New York",
//       "47. Louisiana State University, Baton Rouge, Louisiana (Only UG)",
//       "48. Worcester Polytechnic Institute, Worcester, Massachusetts",
//       "49. Washington State University – Pullman, Tri Cities, Everett, Vancouver, and Spokane Campus",
//       "50. University of Nebraska-Lincoln, Lincoln, Nebraska (Only UG)",
//       "51. University of Alabama at Birmingham, Birmingham, Alabama",
//       "52. Virginia Commonwealth University, Richmond, Virginia",
//       "53. Saint Louis University, St. Louis, Missouri",
//       "54. Missouri University of Science and Technology, Rolla, Missouri",
//       "55. University of Massachusetts Lowell, Lowell, Massachusetts",
//       "56. Clark University, Worcester, Massachusetts",
//       "57. Massachusetts College of Pharmacy and Health Sciences, Boston, Massachusetts (MCPHS University)",
//       "58. University of Massachusetts, Boston, Massachusetts (UG, PG Pathway and Direct Entry)",
//       "59. University of Massachusetts, Dartmouth, Massachusetts",
//       "60. Suffolk University, Boston, Massachusetts",
//       "61. University of New Hampshire, Durham, New Hampshire",
//       "62. Adelphi University, New York- Garden City and Manhattan Campus",
//       "63. University of Idaho, Moscow, Idaho",
//       "64. San Jose State University, San Jose, California",
//       "65. San Francisco State University, San Francisco, California",
//       "66. California State University, Los Angeles, California",
//       "67. California State University, Chico, California",
//       "68. California State University, Northridge, California",
//       "69. California State University, Fresno, California",
//       "70. California State University, East Bay, California",
//       "71. California State University, Channel Islands, California",
//       "72. California State University, Sacramento, California",
//       "73. California State University, Bakersfield, California",
//       "74. California State University, Dominguez Hills, California",
//       "75. California State University, Stanislaus, California",
//       "76. California State University, San Bernardino, California",
//       "77. Sonoma State University, Rohnert Park, California",
//       "78. California State Polytechnic University, Pomona (College of the Extended University)",
//       "79. University of California, Irvine, California (Division of Continuing Education)",
//       "80. University of California, Berkeley Extension, California",
//       "81. University of California, Santa Cruz, Silicon Valley Extension (Professional Education)",
//       "82. University of California, Santa Cruz, Silicon Valley Extension (Professional Education)",
//       "83. University of Central Florida, Orlando, Florida (Only PG)",
//       "84. New Jersey Institute of Technology, Newark, New Jersey",
//       "85. Rochester Institute of Technology, Rochester, New York",
//       "86. Fairleigh Dickinson University, Teaneck, New Jersey",
//       "87. Portland State University, Portland, Oregon (Only UG)",
//       "88. Florida Institute of Technology, Melbourne, Florida",
//       "89. Pace University, Westchester & New York City Campus",
//       "90. Drew University, Madison, New Jersey",
//       "91. Whittier College, Whittier, California (Only UG)",
//       "92. Savannah College of Art and Design, Savannah and Atlanta Campus, Georgia",
//       "93. DePaul University, Chicago, Illinois",
//       "94. University of South Dakota, Vermillion, South Dakota",
//       "95. University of Hartford, West Hartford, Connecticut (Direct Entry and UG/PG Pathway)",
//       "96. Sacred Heart University, Fairfield, Connecticut",
//       "97. Florida International University,",
//       "98. Kent State University, Kent, Ohio",
//       "99. The University of Toledo, Toledo, Ohio (Only UG)",
//       "100. University of Denver, Colorado (Daniel’s College of Business only)",
//     ],
//     cr: [
//       "Mechanical Engineering",
//       "Electrical Engineering",
//       "Civil Engineering",
//       "Computer Engineering",
//       "Aerospace Engineering",
//       "Finance",
//       "Marketing",
//       "Operations Management",
//       "Entrepreneurship",
//       "Human Resource Management",
//       "Artificial Intelligence",
//       "Data Science",
//       "Cyber Security",
//       "Software Development",
//       "Cloud Computing",
//       "Biotechnology",
//       "Physics",
//       "STEM MBA",
//       "Chemistry",
//       "Mathematics",
//       "Pharmacy",
//       "Public Health",
//       "Nursing",
//       "Biomedical Sciences",
//     ],
//   },
//   {
//     cn: "Canada",
//     un: [
//       "1. University of Alberta, Edmonton, Alberta(Only UG)",
//       "2. University of Waterloo, Waterloo, Ontario",
//       "3. University of Ottawa, Ottawa, Ontario",
//       "4. Queen's University, Kingston, Ontario (Only UG)",
//       "5. University of Calgary Continuing Education, Calgary, Alberta",
//       "6. Dalhousie University, Halifax, Nova Scotia",
//       "7. University of Victoria in Partnership with Kaplan, Victoria, British Columbia",
//       "8. York University, School of Continuing Education, Toronto, Ontario",
//       "9. University of Guelph, Guelph and Ridgetown Campus, Ontario",
//       "10. University of Windsor, Windsor, Ontario",
//       "11. University of Manitoba, Winnipeg, Manitoba",
//       "12. Memorial University of Newfoundland, St. John's, Newfoundland and Labrador (Only PG)",
//       "13. Memorial University of Newfoundland, Grenfell Campus, Newfoundland and Labrador (Only UG)",
//       "14. University of New Brunswick, Fredericton and Saint John Campus, New Brunswick",
//       "15. Carleton University, Ottawa, Ontario",
//       "16. Toronto Metropolitan University, Toronto, Ontario",
//       "17. University of Regina, Regina, Saskatchewan",
//       "18. Brock University, St. Catharines, Ontario",
//       "19. Wilfrid Laurier University, Waterloo, Ontario",
//       "20. University of Lethbridge, Lethbridge, Alberta (Only UG)",
//       "21. Lakehead University, Thunder Bay, Ontario",
//       "22. University of Winnipeg, Winnipeg, Manitoba",
//       "23. University of Prince Edward Island, Charlottetown, Prince Edward Island",
//       "24. Acadia University, Wolfville, Nova Scotia (Only UG)",
//       "25. St. Francis Xavier University, Antigonish, Nova Scotia",
//       "26. University of Northern British Columbia, Prince George, British Columbia",
//       "27. Laurentian University, Sudbury, Ontario (Except students from South Asia)",
//       "28. Thompson Rivers University, Kamloops, British Columbia",
//       "29. Ontario Tech University, Oshawa, Ontario",
//       "30. Mount Saint Vincent University, Halifax, Nova Scotia",
//       "31. Trent University, Peterborough, Ontario",
//       "32. Trinity Western University, Langley, British Columbia",
//       "33. Royal Roads University, Victoria, British Columbia",
//       "34. Fairleigh Dickinson University, Vancouver, British Columbia",
//       "35. Simon Fraser University through Fraser International College, Burnaby, British Columbia (Only UG)",
//       "36. University of Alberta in Partnership with Kaplan, Edmonton, Alberta (Foundation programs)",
//       "37. Wilfrid Laurier University through Wilfrid Laurier International College, Brantford, Ontario (Only UG)",
//       "38. University of Manitoba through International College of Manitoba, Winnipeg, Manitoba (Only UG)",
//       "39. University of Lethbridge through ULethbridge International College Calgary (UICC), Calgary, Alberta (Only UG)",
//       "40. Toronto Metropolitan University through Toronto Metropolitan International College, Toronto, Ontario (Only UG)",
//       "41. Vancouver Island University, Nanaimo, British Columbia",
//       "42. St. Thomas University, Fredericton, New Brunswick (Only UG)",
//       "43. University Canada West, Vancouver, British Columbia",
//       "44. New York Institute of Technology, Vancouver, British Columbia",
//       "45. Nipissing University, North Bay, Ontario",
//       "46. Adler University, Vancouver, British Columbia",
//       "47. King’s University College (University of Western Ontario), London, Ontario",
//       "48. Cape Breton University, Sydney, Nova Scotia",
//       "49. Capilano University, North Vancouver, British Columbia",
//       "50. Kwantlen Polytechnic University, Surrey, British Columbia",
//       "51. University of the Fraser Valley, Abbotsford, British Columbia",
//       "52. University of the Fraser Valley",
//       "53. Mount Allison University, Sackville, New Brunswick",
//       "54. MacEwan University, Edmonton, Alberta (Only UG)",
//       "55. University of Niagara Falls, Niagara, Ontario",
//       "56. University of Niagara Falls, Niagara, Ontario",
//       "57. Crandall University, Moncton and Sussex, New Brunswick",
//       "58. City University in Canada, Calgary and Edmonton, Alberta (Master of Education in Leadership program only)",
//       "59. City University in Canada, Vancouver, British Columbia (Master of Education in Leadership program only)",
//       "60. Providence University College, Winnipeg, Manitoba (Master of Management program only)",
//       "61. Niagara University, Vaughan, Ontario (Only PG)",
//       "62. International Business University, Toronto, Ontario (Except students from South Asia and Africa)",
//       "63. Seneca Polytechnic, Toronto, Ontario",
//       "64. Humber Polytechnic, Toronto, Ontario",
//       "65. George Brown College, Toronto, Ontario",
//       "66. Sheridan College, Oakville, Ontario",
//       "67. Bow Valley College, Calgary, Alberta",
//       "68. St. Clair College of Applied Arts & Technology, Windsor, Ontario",
//       "69. Douglas College, New Westminster, British Columbia (Except students from Punjab, Haryana and Chandigarh)",
//       "70. Southern Alberta Institute of Technology, Calgary, Alberta",
//       "71. Northern Alberta Institute of Technology (NAIT), Edmonton, Alberta",
//       "72. Niagara College, Welland, Ontario",
//       "73. Fanshawe College, London, Ontario",
//       "74. Durham College, Oshawa, Ontario",
//       "75. Fleming College, Peterborough, Ontario",
//       "76. North Island College, Vancouver Island, British Columbia",
//       "77. Georgian College, Barrie, Ontario",
//       "78. Langara College, Vancouver, British Columbia (Except students from Punjab and Haryana)",
//       "79. Lakeland College, Lloydminster and Vermilion, Alberta",
//       "80. Cambrian College, Sudbury, Ontario",
//       "81. Manitoba Institute of Trades and Technology, Winnipeg, Manitoba",
//       "82. Conestoga College, Kitchener, Ontario",
//       "83. College of New Caledonia, Prince George, British Columbia",
//       "84. Saskatchewan Polytechnic, Saskatoon, Saskatchewan",
//       "85. LaSalle College, Montreal and Vancouver",
//       "86. College of the Rockies, Cranbrook, British Columbia",
//       "87. Northern Lights College, Dawson Creek, British Columbia",
//       "88. Northern College, Timmins, Ontario",
//       "89. Booth University College, Winnipeg, Manitoba",
//       "90. St. Lawrence College, Kingston, Ontario",
//       "91. Lambton College, Sarnia and Ottawa, Ontario",
//       "92. Selkirk College, Castlegar, British Columbia",
//       "93. Assiniboine College, Brandon, Winnipeg and Dauphin Campus, Manitoba",
//       "94. Keyano College, Fort McMurray, Alberta",
//       "95. Canadore College, North Bay, Ontario (Except students from Punjab and Haryana)",
//       "96. Acsenda School of Management, Vancouver, British Columbia",
//       "97. Vancouver Film School, Vancouver, British Columbia",
//       "98. Vancouver Community College, Vancouver, British Columbia",
//       "99. British Columbia Institute of Technology, Burnaby, British Columbia",
//       "100. Medicine Hat College, Medicine Hat, Alberta",
//     ],
//     cr: [
//       "Engineering",
//       "Management",
//       "Information technology",
//       "Health Sciences",
//       "Financial accounting",
//       "Human Resources",
//       "Journalism",
//       "Architecture",
//       "Business",
//       "Agricultural and forestry",
//       "Project management",
//       "Psychology",
//       "Applied Health",
//       "Computer Engineering",
//       "Computer programming",
//       "Cyber security",
//       "Data science",
//       "Diploma in Accounting",
//       "Hospitality management studies",
//       "Master of Business Administration",
//       "Animation and Multimedia courses",
//     ],
//   },
//   {
//     cn: "Uk",
//     un: [
//       "1. University of Bristol, Bristol, England",
//       "2. University of Glasgow, Glasgow, Scotland",
//       "3. University of Glasgow",
//       "4. University of Southampton, Southampton, England",
//       "5. University of Birmingham, Birmingham, England",
//       "6. University of Leeds, Leeds, England",
//       "7. Durham University, Durham, England",
//       "8. The University of Sheffield, Sheffield, England",
//       "9. University of Nottingham, Nottingham, England",
//       "10. Queen Mary University of London, London, England",
//       "11. Newcastle University, Newcastle upon Tyne, England",
//       "12. Lancaster University, Lancaster, England",
//       "13. University of Bath, Bath, England",
//       "14. University of Liverpool, Liverpool, England",
//       "15. The University of Exeter, Exeter, England",
//       "16. University of Reading, Reading, England",
//       "17. Cranfield University, Cranfield, England",
//       "18. University of York, York, England",
//       "19. Cardiff University, Cardiff, Wales",
//       "20. Queen`s University Belfast, Belfast, Northern Ireland",
//       "21. Loughborough University, Loughborough & London, England",
//       "22. University of Aberdeen, Aberdeen, Scotland",
//       "23. University of Sussex, Brighton, England",
//       "24. Heriot Watt University, Edinburgh, Scotland",
//       "25. University of Strathclyde, Glasgow, Scotland",
//       "26. University of Surrey , Guildford, England",
//       "27. University of Leicester, Leicester, England",
//       "28. Swansea University, Swansea, Wales",
//       "29. University of East Anglia, Norwich, England",
//       "30. Brunel University of London, London, England",
//       "31. City St George's, University of London, London, England",
//       "32. University of Kent, Canterbury, England",
//       "33. Oxford Brookes University, Oxford, England",
//       "34. University of Dundee, Dundee, Scotland",
//       "35. Aston University, Birmingham, England",
//       "36. University of Stirling, Stirling, Scotland",
//       "37. University of Essex, Colchester, England",
//       "38. Bangor University, Bangor, Wales",
//       "39. Royal Holloway, University of London, Egham, England",
//       "40. The University of Huddersfield, Huddersfield, England",
//       "41. SOAS University of London, London, England",
//       "42. The University of Huddersfield, London, England",
//       "43. University of Hull, Hull, England",
//       "44. University of Hull, London Campus, England",
//       "45. Coventry University, Coventry & London, England",
//       "46. University of Bradford, Bradford, England",
//       "47. Northumbria University, Newcastle upon Tyne & London, England",
//       "48. Nottingham Trent University, Nottingham, England",
//       "49. Manchester Metropolitan University, Manchester, England",
//       "50. Kingston University, Kingston, England",
//       "51. University of Portsmouth, Portsmouth & London, England",
//       "52. University of Plymouth, Plymouth, England",
//       "53. Aberystwyth University, Aberystwyth, Wales",
//       "54. Goldsmiths, University of London, London, England",
//       "55. University of Greenwich, London, England",
//       "56. De MontFort University, Leicester, England",
//       "57. Middlesex University, London, England",
//       "58. University of the West of England, Bristol, England",
//       "59. Keele University, Keele, England",
//       "60. University of Brighton, Brighton, England",
//       "61. Edinburgh Napier University, Edinburgh, Scotland",
//       "62. London South Bank University, London, England",
//       "63. University of Hertfordshire, Hatfield, England",
//       "64. University of Lincoln, Lincoln, England",
//       "65. University of East London, London, England",
//       "66. University of Salford, Manchester, England",
//       "67. Robert Gordon University, Aberdeen, Scotland",
//       "68. Robert Gordon University, Aberdeen, Scotland",
//       "69. University of Lancashire, Preston, England",
//       "70. London Metropolitan University, London, England",
//       "71. Birmingham City University, Birmingham, England",
//       "72. Sheffield Hallam University, Sheffield, England",
//       "73. The University of Northampton, Northampton, England",
//       "74. Leeds Beckett University, Leeds, England",
//       "75. University of Derby, Derby, England",
//       "76. Canterbury Christ Church University, Canterbury, England",
//       "77. University of Wolverhampton, Wolverhampton, England",
//       "78. Anglia Ruskin University, Cambridge & Chelmsford, England (Except Punjab and Haryana)",
//       "79. Teesside University (Except Namakkal & Punjab), Middlesbrough and London Campus",
//       "80. University of Suffolk, London, England",
//       "81. University of Suffolk, London, England",
//       "82. University of the West of Scotland, Paisley, Scotland",
//       "83. University of the West of Scotland, London Campus, England",
//       "84. University of South Wales (Except Punjab & Haryana), Cardiff, Wales",
//       "85. University of South Wales",
//       "86. University of Roehampton, London, England",
//       "87. University of Staffordshire, Stoke-on-Trent, England",
//       "88. University of Sunderland, Sunderland & London, England",
//       "89. University of Bedfordshire, Luton, England",
//       "90. Cardiff Metropolitan University, Cardiff , Wales",
//       "91. University of Chester, Chester, England",
//       "92. University of Gloucestershire, Gloucester, England",
//       "93. University of West London, London, England",
//       "94. York St John University, York, England",
//       "95. University of Greater Manchester, Bolton, England",
//       "96. Abertay University, Dundee, Scotland",
//       "97. Liverpool Hope University, Liverpool, England",
//       "98. University of Wales Trinity Saint David, London, Birmingham and Swansea Campus, England & Wales",
//       "99. St. Mary’s University, Twickenham, England",
//       "100. Southampton Solent University, Southampton, England",
//     ],
//     cr: [
//       "Architecture",
//       "Engineering",
//       "Law",
//       "Computer Science",
//       "Business analytics",
//       "MBA",
//       "Medicine",
//       "Data science",
//       "Financial accounting",
//       "Psychology",
//       "Economics",
//       "Education",
//       "Nursing",
//       "Fashion and interior designing",
//       "Bachelor of medicine, bachelor of Surgery",
//     ],
//   },
//   {
//     cn: "Australia",
//     un: [
//       "1. The University of New South Wales, Sydney",
//       "2. Monash University, Melbourne",
//       "3. The University of Queensland, Brisbane)",
//       "4. University of Western Australia, Perth",
//       "5. The University of Adelaide,",
//       "6. University of Technology Sydney, Sydney",
//       "7. Adelaide University, Adelaide",
//       "8. Adelaide University, Adelaide",
//       "9. RMIT University, Melbourne",
//       "10. Macquarie University, Sydney",
//       "11. Macquarie University",
//       "12. University of Wollongong, Wollongong",
//       "13. Deakin University, Melbourne, Geelong & Warrnambool Campus",
//       "14. Queensland University of Technology, Brisbane",
//       "15. La Trobe University, Melbourne & Sydney",
//       "16. Griffith University, Gold Coast & Brisbane (CRICOS Code 00233E)",
//       "17. Swinburne University of Technology, Melbourne",
//       "18. University of Tasmania, Hobart, Launceston, Sydney",
//       "19. University of Tasmania, Melbourne",
//       "20. Flinders University, Adelaide",
//       "21. University of South Australia, Adelaide",
//       "22. Western Sydney University, Sydney City Campus",
//       "23. Murdoch University, Perth Campus",
//       "24. University of Canberra, Sydney Hills",
//       "25. James Cook University, Townsville, Cairns & Brisbane",
//       "26. CQUniversity Australia, Sydney, Melbourne, Brisbane & Perth",
//       "27. Charles Darwin University, Darwin",
//       "28. Victoria University, Sydney & Brisbane",
//       "29. Victoria University, Sydney",
//       "30. Charles Sturt University, Sydney & Melbourne",
//       "31. University of the Sunshine Coast, Adelaide",
//       "32. The University of Notre Dame Australia, Fremantle",
//       "33. S P Jain School of Global Management, Sydney Campus",
//       "34. UNSW College, Sydney",
//       "35. The University of Adelaide College",
//       "36. UTS College, Sydney",
//       "37. Charles Darwin University International",
//       "38. Engineering Institute of Technology,",
//       "39. ECA College of Health Sciences, Brisbane & Sydney",
//       "40. Asia Pacific International College, Sydney & Melbourne",
//       "41. Higher Education Leadership Institute, Melbourne",
//       "42. Le Cordon Bleu, Adelaide, Sydney, Melbourne & Perth",
//       "43. Kaplan Business School, Sydney (Only PG)",
//       "44. International College of Management Sydney",
//       "45. Academy of Interactive Technology, Sydney",
//       "46. Academy of Information Technology, Sydney",
//       "47. Excelsia University College, Sydney",
//       "48. Ironwood Institute Adelaide, Adelaide",
//       "49. Australian College of Applied Professions, Sydney",
//       "50. The University of Newcastle College of International Education, Newcastle",
//       "51. Curtin College, Perth",
//       "52. Deakin College, Melbourne",
//       "53. South Australia Institute of Business & Technology, Adelaide",
//       "54. Griffith College, Gold Coast & Brisbane",
//       "55. La Trobe College, Melbourne",
//       "56. Sydney Institute of Business & Technology, Sydney",
//       "57. Edith Cowan College",
//       "58. Eynesbury College, Adelaide",
//       "59. University of Canberra College, Canberra",
//       "60. Russo Business School, Brisbane",
//       "61. LaSalle College, Melbourne",
//       "62. Sarina Russo Institute, Brisbane",
//       "63. Analytics Institute of Australia, Melbourne",
//     ],
//     cr: [
//       "Engineering",
//       "Accountancy",
//       "Hospitality",
//       "Business analytics",
//       "Nursing",
//       "Computer Science",
//       "Medicine",
//       "Psychology",
//       "Actuarial science",
//       "Architecture",
//       "Earth sciences",
//       "Agricultural science",
//       "Construction managers",
//       "Education",
//       "Civil Engineering",
//       "Barnbougle Lost Farm Golf Resort",
//       "BBA in Australia",
//       "Management",
//       "Core Engineering",
//       "Information technology",
//       "Kingston Heath Golf Club",
//       "Medicine courses in Australia",
//       "Chef",
//       "Financial Analyst",
//     ],
//   },
//   {
//     cn: "New Zealand",
//     un: [
//       "1. University of Auckland, Auckland",
//       "2. University of Otago, Dunedin",
//       "3. Massey University, Palmerston North",
//       "4. Victoria University of Wellington, Wellington",
//       "5. University of Waikato, Hamilton",
//       "6. University of Canterbury, Christchurch",
//       "7. Lincoln University, Lincoln",
//       "8. Auckland University of Technology, Auckland",
//       "9. Unitec Institute of Technology, Auckland",
//       "10. Otago Polytechnic, Dunedin & Auckland",
//       "11. Manukau Institute of Technology - Te Pūkenga, Auckland",
//       "12. Ara Institute of Canterbury, Christchurch",
//       "13. Eastern Institute of Technology, Napier",
//       "14. Waikato Institute of Technology (Wintec), Hamilton",
//       "15. Waikato Institute of Technology (Wintec) - Te Pūkenga",
//       "16. Nelson Marlborough Institute of Technology (NMIT), Nelson & Blenheim",
//       "17. Whitireia New Zealand, Porirua",
//       "18. Southern Institute of Technology, Invercargill",
//       "19. Wellington Institute of Technology (WelTec), Wellington",
//       "20. Western Institute of Technology at Taranaki (WITT), New Plymouth",
//       "21. North Tec, Whangarei",
//       "22. The Universal College of Learning (UCOL), Palmerston North",
//       "23. Toi Ohomai Institute of Technology, Rotorua & Tauranga",
//       "24. New Zealand Skills and Education Group, Auckland",
//       "25. Pacific International Hotel Management School, New Plymouth",
//       "26. New Zealand Tertiary College (NZTC), Auckland",
//       "27. Future Skills Academy, Auckland",
//       "28. UC International College, Christchurch",
//       "29. The University of Auckland International College",
//       "30. University of Waikato College, Hamilton",
//       "31. Whitecliffe College of Arts and Design, Auckland & Christchurch",
//       "32. Whitecliffe College of Fashion and Sustainability, Auckland & Wellington",
//       "33. Whitecliffe College of Technology & Innovation, Auckland, Wellington & Christchurch",
//       "34. Le Cordon Bleu, Wellington",
//       "35. New Zealand Airline Academy, Oamaru",
//       "36. AcademyEX Education, Auckland",
//       "37. New Zealand Management Academies (NZMA), Auckland",
//       "38. New Zealand Industry Training Enterprise (NZITE), Auckland",
//     ],
//     cr: [
//       "IT & Computer Science",
//       "MBA",
//       "Healthcare",
//       "Engineering",
//       "Tourism/Hospitality Management",
//       "Law",
//       "Architecture",
//       "Sports Management",
//       "Agriculture",
//       "Accounting",
//       "Animation and Web Design",
//     ],
//   },
//   {
//     cn: "France",
//     un: [
//       "1. INSEEC Business School, Paris",
//       "2. NEOMA Business School, Rouen",
//       "3. ESCE International Business School, Paris",
//       "4. ECE Engineering School, Paris",
//       "5. (Navitas) ICN International College, Paris",
//       "6. SupdePub School of Creation and Communication, Paris",
//       "7. HEIP, School of International and Political Studies, Paris",
//       "8. Excelia Group, La Rochelle",
//       "9. ICN Business School, Nancy and Paris Campus",
//       "10. Kedge Business School, Talence",
//       "11. Montpellier Business School, Montpellier",
//       "12. ESSCA School of Management, Angers",
//       "13. EM Normandie Business School, Paris",
//       "14. Clermont School of Business, Clermont-Ferrand",
//       "15. ESC Clermont Business School, Clermont-Ferrand",
//       "16. Skema Business School, Paris",
//       "17. Burgundy School of Business, Dijon",
//       "18. Institut supérieur d`électronique de Paris (ISEP), Paris",
//       "19. EPITA - School of Engineering and Computer Science, Paris",
//       "20. ESIGELEC, Rouen",
//       "21. Institut supérieur du commerce de Paris - ISC, Paris",
//       "22. Le Cordon Bleu, Paris",
//       "23. De Vinci Higher Education, Paris",
//       "24. College de Paris, Paris",
//       "25. Queen Mary University of London, Paris",
//       "26. Instituto Marangoni Fashion and Design School, Paris",
//       "27. The American Business School of Paris, Paris",
//       "28. Ecole Ducasse, Paris",
//       "29. Berlin School of Business and Innovation, Paris",
//       "30. ICD Business School, Paris",
//       "31. Schiller International University, Paris Campus",
//       "32. École de Management Appliqué, Paris",
//       "33. Paris School of Business, Paris",
//       "34. ESDES School of Business and Management, Lyon",
//       "35. EPITECH, Paris",
//       "36. HEAD School of Law, Paris",
//     ],
//     cr: [
//       "Engineering",
//       "Fashion design",
//       "Computer Science",
//       "Data science",
//       "Film Studies",
//       "Finance",
//       "Hospitality management studies",
//       "Luxury brand Management",
//       "Medicine",
//       "Engineering and technology",
//     ],
//   },
//   {
//     cn: "Germany",
//     un: [
//       "1. Constructor University",
//       "2. Jacobs University",
//       "3. Steinbeis University, Berlin (Only PG)",
//       "4. SRH University, Berlin, Hamburg, Leipzig, Dresden, Munich and Heidelberg Campuses",
//       "5. SRH Berlin University of Applied Sciences",
//       "6. SRH Fernhochschule – The Distance Learning University, Riedlingen",
//       "7. Northern Institute of Technology Management (NIT), Hamburg",
//       "8. Hamburg University of Technology (TUHH), Hamburg",
//       "9. FOM Hochschule - University of Applied Sciences for Economics and Management, Essen",
//       "10. EBS University, Wiesbaden",
//       "11. International School of Management, Dortmund",
//       "12. International University of Applied Sciences, Berlin and Bad Honnef",
//       "13. CBS International Business School, Cologne",
//       "14. Arden University, Berlin",
//       "15. GISMA University of Applied Sciences GmbH, Berlin",
//       "16. New European College, Munich",
//       "17. EU Business School, Munich",
//       "18. Munich Business School, Munich",
//       "19. Accadis Hochschule Bad Homburg - University of Applied Sciences, Bad Homburg",
//       "20. Berlin School of Business and Innovation, Berlin",
//       "21. Fresenius University of Applied Sciences, Idstein",
//       "22. University of Europe for Applied Sciences, Hamburg",
//       "23. Hochschule Macromedia University of Applied Sciences, Munich",
//       "24. ICN Business School, Berlin Campus",
//       "25. Navitas - Lancaster University, Leipzig",
//       "26. EIIE Eurasia Institute for International Education GmbH, Berlin (Except students from Gujarat, Punjab and Haryana)",
//       "27. University Targu Mures Medical Campus, Hamburg (UMCH)",
//       "28. Media Design University of Applied Sciences, Berlin",
//       "29. Schiller International University, Heidelberg Campus",
//       "30. PFH – Private University of Applied Sciences, Göttingen",
//     ],
//     cr: [
//       "Engineering",
//       "Computer Science and IT",
//       "Business Management",
//       "Social Sciences",
//       "Humanities and Creative Arts",
//     ],
//   },
//   {
//     cn: "Denmark",
//     un: [
//       "1. Aarhus University, Aarhus",
//       "2. University of Southern Denmark, Odense and Sonderborg Campus",
//       "3. International Business Academy, Kolding",
//       "4. VIA University College, Horsens and Herning Campus",
//     ],
//     cr: [
//       "Engineering and Technology",
//       "Business and Management",
//       "Life Sciences and Environmental Sciences",
//       "Design and Creative Arts",
//       "Social Sciences and Humanities",
//     ],
//   },
//   {
//     cn: "Finland",
//     un: [
//       "1. Aalto University, Espoo",
//       "2. University of Turku, Turku",
//       "3. LUT University, Lappeenranta",
//       "4. Tampere University, Tampere",
//       "5. University of Jyväskylä, Jyväskylä",
//       "6. Tampere University of Applied Sciences (TAMK), Tampere",
//       "7. Turku University of Applied Sciences, Turku",
//       "8. University of Eastern Finland, Kuopio",
//       "9. LAB University of Applied Sciences, Lahti",
//       "10. University of Vaasa, Vaasa",
//       "11. Vaasa University of Applied Sciences VAMK, Vaasa",
//       "12. Karelia University of Applied Sciences, Joensuu",
//       "13. Metropolia University of Applied Sciences, Helsinki",
//       "14. Satakunta University of Applied Sciences (SAMK), Pori",
//       "15. Arcada University of Applied Sciences, Helsinki",
//       "16. Hanken School of Economics, Helsinki",
//     ],
//     cr: [
//       "Information Technology (IT),",
//       "Business Administration,",
//       "Engineering,",
//       "Sustainability studies and Environmental Sciences",
//       "Health Sciences and Biotechnology",
//       "Arts, Design, and Architecture",
//       "Social Sciences",
//     ],
//   },
//   {
//     cn: "Italy",
//     un: [
//       "1. University of Padua, Padua",
//       "2. Istituto Europeo di Design - IED, Milan",
//       "3. Istituto Marangoni Fashion and Design School, (Milan and Florence Campus)",
//       "4. Nuova Accademia di Belle Arti (NABA School), Milan",
//       "5. Domus Academy, Milan",
//       "6. Raffles Milano- Instituto Moda e Design, Milan",
//       "7. LUISS Guido Carli, Rome",
//       "8. Guglielmo Marconi University, Rome",
//       "9. Polimi Graduate School of Management, Italy",
//     ],
//     cr: [
//       "Hospitality Management",
//       "Business Management",
//       "Economics",
//       "Humanities",
//       "Masters in fashion design",
//       "BA in Italy",
//       "Engineering",
//       "International Relations",
//       "MBA",
//       "Sciences",
//       "Fashion and luxury goods management",
//     ],
//   },
//   {
//     cn: "Cyprus",
//     un: [
//       "University of Nicosia, Nicosia",
//       "University of Central Lancashire (UCLAN), Pyla",
//       "Neapolis University Pafos, Pafos",
//     ],
//     cr: [
//       "Business & Management,",
//       "Engineering & Technology,",
//       "Hospitality & Tourism,",
//       "Computer Science & IT",
//       "Psychology",
//       "Law",
//       "Health Sciences",
//       "Social Sciences",
//       "Aviation",
//       "Food & Beverage Studies",
//       "Architecture Studies",
//     ],
//   },
//   {
//     cn: "Malta",
//     un: [
//       "1. Queen Mary University of London, Malta Campus",
//       "2. Ascencia Business School Malta",
//       "3. College De Paris, Malta Campus (Ascencia Malta)",
//       "4. Idea Academy, Malta",
//       "5. London School of Commerce, Malta Campus",
//       "6. Global Malta College (Except students from Punjab)",
//       "7. Saint Martin’s Institute of Higher Education",
//       "8. Global Business School – GBS Malta Campus",
//       "9. Learnkey Training Institute",
//       "10. Yhank Institute, Malta",
//     ],
//     cr: [
//       "Engineering",
//       "Information technology",
//       "Economics",
//       "Medicine",
//       "Hospitality management studies",
//       "Arts and design",
//       "Business Administration",
//       "Management",
//       "Environmental science, ecology",
//       "Law",
//       "Natural Sciences",
//       "Social Sciences",
//       "Humanities",
//       "Media and communication",
//     ],
//   },
//   {
//     cn: "Switzerland",
//     un: [
//       "1. University of Zurich, Zürich (Only PG)",
//       "2. GLION Institute of Higher Education, Montreux",
//       "3. EU Business School, Montreux and Geneva",
//       "4. Business & Hotel Management School (BHMS), Lucerne",
//       "5. Swiss Hotel Management School (SHMS), Montreux and Leysin",
//       "6. Geneva Business School, Geneva",
//       "7. Webster University Geneva, Geneva",
//       "8. Swiss School of Business and Management (SSBM), Geneva",
//       "9. International Management Institute (IMI), Kastanienbaum, Luzern",
//       "10. Cesar Ritz, Montreux",
//       "11. International University in Geneva, Geneva",
//       "12. Hotel & Tourism Management Institute Switzerland (HTMi), Lucerne",
//       "13. Les Roches, Montana",
//       "14. lesroches.edu/campuses/crans-montana/",
//       "15. Culinary Arts Academy (CAA), Le Bouveret and Lucerne",
//       "16. Hotel Institute Montreux (HIM), Montreux",
//       "17. American Institute of Applied Sciences in Switzerland, La Tour-de-Peilz",
//       "18. EHL Swiss School of Tourism and Hospitality, Passugg Campus",
//       "19. EHL Hospitality Business School, Lausanne Campus",
//       "20. Swiss Education Academy, Montreux",
//       "21. Swiss Educational College, Weggis",
//       "22. Bella Vista Institute of Higher Education Switzerland (BVIS), Altdorf and Montreux",
//       "23. S P Jain School of Global Management, India Campus",
//     ],
//     cr: [
//       "Business management,",
//       "Finance,",
//       "Engineering, law,",
//       "Computer science (IT)",
//       "Hospitality & Tourism Management",
//       "Applied Mathematics",
//       "Artificial Intelligence",
//       "Interdisciplinary Sciences",
//       "Quantitative & Systems Biology",
//       "Hotel & Hospitality Management",
//       "International Business",
//       "Mathematics",
//       "Media & Films",
//       "Psychology",
//       "Arts",
//       "Science",
//       "Education & Training",
//       "Medicine and Healthcare",
//     ],
//   },
//   {
//     cn: "Sweden",
//     un: [
//       "1. Uppsala University, Uppsala",
//       "2. Linnaeus University, Kalmar and Växjö",
//       "3. University of Skövde, Skovde",
//       "4. Halmstad University, Halmstad",
//       "5. University West, Trollhättan",
//       "6. Jönköping University, Jönköping",
//       "7. Dalarna University, Falun",
//       "8. Kristianstad University, Kristianstad",
//       "9. Karlstad University, Karlstad",
//       "10. Hyper Island University, Stockholm",
//     ],
//     cr: [
//       "Engineering",
//       "Computer Science",
//       "Environmental studies",
//       "Law",
//       "Mathematics",
//       "Public Health",
//       "Management",
//       "Humanities",
//       "Social Sciences",
//       "Design and Creative Arts",
//       "Plant and Forest biotechnology",
//     ],
//   },
//   {
//     cn: "Hungary",
//     un: [
//       "1. University of Debrecen, Debrecen",
//       "2. Budapest University of Economics and Business, Budapest",
//       "3. University of Pécs, Pécs",
//       "4. Szechenyi Istvan University (University of Gyor), Gyor",
//       "5. International Business School (IBS), Budapest (Except students from Punjab & South India)",
//       "6. Budapest Metropolitan University of Applied Science, Budapest",
//       "7. Wekerle Business School, Budapest",
//     ],
//     cr: [
//       "Engineering",
//       "Business & Finance",
//       "Medicine & Healthcare",
//       "Computer & IT Humanities",
//       "Music",
//     ],
//   },
//   {
//     cn: "Netherlands",
//     un: [
//       "1. University of Twente, Enschede",
//       "2. Radboud University, Nijmegen",
//       "3. Maastricht School of Management, Maastricht",
//       "4. Wittenborg University of Applied Sciences, Amsterdam and Apeldoorn Campus",
//       "5. Tio Business School, Utrecht",
//       "6. Tio University of Applied Sciences",
//       "7. Unknown University of Applied Sciences, Amsterdam, The Hague",
//       "8. Global School of Entrepreneurship",
//       "9. The Hague University of Applied Sciences (UG Pathway), Hague",
//       "10. University of Applied Sciences Europe, Amsterdam",
//     ],
//     cr: [
//       "Engineering",
//       "Business",
//       "Management",
//       "Computer Science",
//       "Finance",
//       "Sciences",
//       "Economics",
//       "Information technology",
//       "International Relations",
//       "MBA",
//       "Natural Sciences",
//       "Social Sciences",
//     ],
//   },
//   {
//     cn: "Ireland",
//     un: [
//       "1. Trinity College Dublin, Dublin",
//       "2. University College Dublin, Dublin",
//       "3. University of Galway, Galway",
//       "4. University College Cork, Cork",
//       "5. Dublin City University, Dublin",
//       "6. University of Limerick, Limerick",
//       "7. Maynooth University, Maynooth",
//       "8. Technological University Dublin, Dublin",
//       "9. South East Technological University (Waterford and Carlow Campus)",
//       "10. Munster Technological University, Cork and Kerry Campus",
//       "11. RCSI University of Medicine and Health Sciences",
//       "12. Royal College of Surgeons in Ireland, Dublin",
//       "13. Atlantic Technological University (Galway and Letterkenny Campus)",
//       "14. Dundalk Institute of Technology, Dundalk",
//       "15. Technological University of the Shannon: Midlands Midwest, Shannon (Limerick and Athlone Campus)",
//       "16. National College of Ireland, Dublin",
//       "17. Dublin Business School, Dublin",
//       "18. Griffith College, Dublin, Cork and Limerick (Campus in 3 cities)",
//       "19. Galway Business School, Galway",
//       "20. Shannon College of Hotel Management, A college of NUI Galway, Galway",
//       "21. Dublin International Foundation College, Dublin",
//       "22. American College Dublin, Dublin",
//       "23. UniHaven College, Maynooth",
//       "24. IBAT College Dublin, Dublin",
//       "25. Independent College, Dublin",
//       "26. CCT College Dublin, Dublin",
//     ],
//     cr: [
//       "Engineering",
//       "Management",
//       "Medicine",
//       "Computer Science",
//       "Computer Science in Ireland",
//       "Data science",
//       "Digital marketing",
//       "Finance",
//       "Science",
//       "Business analytics",
//       "Data analysis",
//       "Engineering in Ireland",
//       "Healthcare",
//       "Pharmaceutical Sciences",
//       "Social Sciences",
//       "Artificial intelligence",
//       "Cloud computing",
//       "Computer security",
//       "Hospitality and Tourism",
//       "Software engineering",
//       "Business Analytics in Ireland",
//       "Medicine in Ireland",
//     ],
//   },
//   {
//     cn: "Singapore",
//     un: [
//       "1. National University of Singapore (SCALE and ISS courses)",
//       "2. Technical University of Munich Asia (Only PG)",
//       "3. Singapore University of Technology and Design (SUTD)",
//       "4. Curtin Singapore",
//       "5. James Cook University (JCU)",
//       "6. Embry Riddle Aeronautical University Asia",
//       "7. SIM Global Education",
//       "8. S P Jain School of Global Management",
//       "9. Management Development Institute of Singapore (MDIS)",
//       "10. PSB Academy",
//       "11. Raffles College of Higher Education",
//       "12. Kaplan Higher Education Academy (KHEA)",
//       "13. Kaplan Financial Education",
//       "14. William Angliss Institute",
//       "15. Nanyang Institute of Management",
//       "16. East Asia Institute of Management",
//       "17. XCL World Academy (Boarding School)",
//     ],
//     cr: [
//       "MBA",
//       "Hospitality and Tourism",
//       "Computer Science",
//       "Law",
//       "Banking",
//       "Management",
//       "Engineering",
//       "Information technology",
//       "Architecture",
//       "Healthcare",
//       "Art",
//       "Bachelor of Medicine and Bachelor of Surgery",
//       "Bachelor of Engineering",
//       "Finance",
//       "Management and engineering",
//       "Mass communication",
//       "Environmental resource management",
//       "Social science",
//       "Urban planning",
//       "BBA in Singapore",
//       "Logistics and supply chain Management",
//       "Postgraduate Diploma in Business Administration",
//     ],
//   },
//   {
//     cn: "Dubai",
//     un: [
//       "1. University of Birmingham, Dubai Campus",
//       "2. University of Wollongong, Dubai Campus",
//       "3. Curtin University, Dubai Campus",
//       "4. Heriot Watt University, Dubai Campus",
//       "5. Murdoch University, Dubai Campus",
//       "6. Canadian University, Dubai",
//       "7. Abu Dhabi University, Abu Dhabi & Dubai",
//       "8. Symbiosis International University, Dubai Campus",
//       "9. Middlesex University, Dubai Campus",
//       "10. Bath Spa University, Ras Al-Khaimah",
//       "11. American University in Dubai, Dubai",
//       "12. De MontFort University, Dubai Campus",
//       "13. University of Hertfordshire, Sharjah Campus",
//       "14. Manipal Academy of Higher Education (MAHE), Dubai Campus",
//       "15. Abu Dhabi University",
//       "16. Birla Institute of Technology and Science (BITS Pilani), Dubai Campus",
//       "17. Rochester Institute of Technology Dubai (RIT Dubai)",
//       "18. Hult International Business School, Dubai Campus",
//       "19. S P Jain School of Global Management, Dubai Campus",
//       "20. University of Bolton Academic Centre, Ras Al Khaimah",
//       "21. EM Normandie, Dubai Campus",
//       "22. HTMI Switzerland, Dubai Campus",
//       "23. American University of Ras Al Khaimah",
//       "24. Synergy University, Dubai Campus",
//       "25. Emirates Aviation University, Dubai",
//       "26. University of Europe for Applied Sciences, Dubai",
//       "27. Istituto Marangoni Fashion and Design School, Dubai",
//       "28. Abu Dhabi Hospitality Academy - Les Roches, Abu Dhabi Campus",
//       "29. Institute of Management Technology (IMT), Dubai",
//       "30. Global Business Studies - GBS Dubai",
//       "31. Idea Academy, Dubai (Except Students from Punjab and Haryana)",
//       "32. UK College of Business and Computing, Dubai Campus",
//       "33. Regent College, Dubai Campus",
//       "34. Institute of Business, Technology and Engineering (IBTE), Dubai",
//     ],
//     cr: [
//       "Management",
//       "Engineering",
//       "Hospitality and Tourism Management",
//       "Medicine and healthcare",
//       "Computer science and IT",
//       "Media and communication",
//       "Architecture",
//       "Financial accounting",
//       "Education",
//       "Art and Design",
//       "Healthcare",
//     ],
//   },
//   {
//     cn: "Malaysia",
//     un: [
//       "1. Monash University, Malaysia Campus",
//       "2. University of Southampton, Malaysia Campus",
//       "3. University of Nottingham, Malaysia Campus",
//       "4. University of Wollongong, Malaysia Campus",
//       "5. Heriot-Watt University, Malaysia Campus",
//       "6. Taylor`s University, Malaysia",
//       "7. Swinburne University, Malaysia Campus",
//       "8. UCSI University, Kuala Lumpur",
//       "9. Asia Pacific University of Technology And Innovation, Kuala Lumpur",
//       "10. Sunway Le Cordon Bleu",
//       "11. Raffles University, Malaysia Campus",
//       "12. Raffles College of Higher Education, Kuala Lumpur",
//       "13. MDIS Malaysia, Gelang Patah",
//     ],
//     cr: [
//       "Engineering",
//       "Accounting",
//       "IT",
//       "Mass communication",
//       "Aerospace engineering",
//       "Architecture",
//       "Biomedical engineering",
//       "Civil Engineering",
//       "Medicine",
//       "Social Sciences",
//       "Computer Science",
//       "Economics",
//       "Electrical engineering",
//       "Environmental studies",
//       "Healthcare courses",
//       "Humanities",
//       "Marketing",
//       "Software engineering",
//       "Management",
//       "Business Administration",
//       "Creative Arts and Media",
//     ],
//   },
//   {
//     cn: "Japan",
//     un: [
//       "International College of Liberal Arts, Kofu",
//       "Tokyo International University, Kawagoe",
//       "Kudan Institute of Japanese language & Culture, Tokyo",
//     ],
//     cr: [
//       "Engineering",
//       "Medicine",
//       "Business",
//       "Agriculture",
//       "Commerce",
//       "Economics",
//       "Education",
//       "Environmental Science",
//       "Language and cultural Studies",
//       "Law",
//       "Sports science",
//     ],
//   },
// ];

// export default data;
